# lightning.pytorch==2.3.0
seed_everything: true
trainer:
  logger: null
  max_epochs: 20
  deterministic: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val_acc'
        mode: 'max'
        save_top_k: 1
        dirpath: null
        filename: null
    - class_path: pytorch_lightning.callbacks.RichProgressBar
data:
  dataset : null
  version : null
  picks : EEG
  sequence_lenght : 21
  preprocessing : null
  target_transform : null
  task : sleep
  batch_size : 32
  fold : 0
model:
  model : null
  picks : null
  sequence_lenght : null
  loss_name : cel
  task : null
