site_name: PhysioEx 
site_url: https://guidogagl.github.io/physioex/
nav:
    - Home: index.md
    - Train: 
      - train CL: train.md
      - networks: 
        - Chambon 2018: train/networks/chambon2018.md
    - Explain: unavailable.md
    - Data: unavailable.md
    - Examples: 
      - Visualize Latent Space: examples/latent_space_visualization.md
    - Contribute: contribute.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  
  favicon: assets/images/logo_bar.svg
  logo: assets/images/logo_bar.svg
  
  features:
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  
repo_name: guidogagl/physioex
repo_url: https://github.com/guidogagl/physioex

plugins:
  - search
  - social
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/guidogagl
    - icon: fontawesome/solid/globe
      link: https://guidogagl.github.io/
    - icon: fontawesome/brands/google-scholar
    #  link: https://scholar.google.com/citations?hl=en&user=8EczeSIAAAAJ&view_op=list_works&authuser=1&gmla=AH70aAXBbb_-rGzDj_dBksWED8IN9ZEu82KU8sbVIEl7KzRmvje06i4p0K4QxpdLOhJnQFneN4VMBPIkc99NwVe0

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

copyright: |
  &copy; 2023 <a href="https://github.com/guidogagl"  target="_blank" rel="noopener">Guido Gagliardi</a>