n_classes: 5
latent_space_dim: 32
batch_size: 32
in_chan: 1
seq_len: 3
T: 29
F: 129
D: 32
nfft: 256
samplerate: 100
lowfreq: 0
highfreq: 50
seqnhidden1: 64
seqnlayer1: 1
attentionsize1: 32
seqnhidden2: 64
seqnlayer2: 1
learning_rate: 1e-4
adam_beta_1: 0.9
adam_beta_2: 0.999
adam_epsilon: 1e-8

#previews parameters are shared with seqsleepnet.yaml

n_concept: 5
concept_dim: 8
#set class_division only if you are in a binary classification problem and in the dataset there are more then 2 classes
#example class_division: ((0,), (1, 2, 3, 4)) it will merge 1, 2, 3, 4 classes in a single class
class_division: ((0,), (1, 2, 3, 4))
training_type: 'end_to_end'
alpha: 1.0

