n_classes: 5
latent_space_dim: 32
batch_size: 32
in_chan: 1
seq_len: 3
T: 29
F: 129
D: 32
nfft: 256
samplerate: 100
lowfreq: 0
highfreq: 50
seqnhidden1: 64
seqnlayer1: 1
attentionsize1: 32
seqnhidden2: 64
seqnlayer2: 1
learning_rate: 1e-4
adam_beta_1: 0.9
adam_beta_2: 0.999
adam_epsilon: 1e-8

#previews parameters are shared with seqsleepnet.yaml

n_concepts: 5
concept_dim: 2


