# Wrapper configuration
model_name: seqsleepnet
model_path: /home/manni/models/seqsleepnet_mass_l3_eeg_to_wrap/fold=-1-epoch=7-step=12872-val_loss=0.63.ckpt
n_proto_per_class: 3
lambda1: 0.04
lambda2: 20

# Wrapped module configuration
n_classes: 5
batch_size: 32
dropOutProb: 0.2
in_channels: 1
seq_len: 3
T: 29
F: 129
D: 32
nfft: 256
samplerate: 100
lowfreq: 0
highfreq: 50
seqnhidden1: 64
seqnlayer1: 1
attentionsize1: 32
seqnhidden2: 64
seqnlayer2: 1
learning_rate: 1e-4
adam_beta_1: 0.9
adam_beta_2: 0.999
adam_epsilon: 1e-8
input_processing: xsleepnet